services:
  stats-server:
    build:
      context: ./stat-svc/stat-svc-service
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/statdb
      SPRING_DATASOURCE_USERNAME: statuser
      SPRING_DATASOURCE_PASSWORD: statpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
    depends_on:
      - stats-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: statdb
      POSTGRES_USER: statuser
      POSTGRES_PASSWORD: statpass
    ports:
      - "5433:5432"
    volumes:
      - stats_db_data:/var/lib/postgresql/data

  ewm-main-service:
    build: ./main-service
    ports: [ "8080:8080" ]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewmdb
      SPRING_DATASOURCE_USERNAME: ewmuser
      SPRING_DATASOURCE_PASSWORD: ewmpass
      STATS_CLIENT_BASE_URL: http://stats-server:9090
    depends_on: [ ewm-db, stats-server ]

  ewm-db:
    image: postgres:16.1
    environment:
        POSTGRES_DB: ewmdb
        POSTGRES_USER: ewmuser
        POSTGRES_PASSWORD: ewmpass
    volumes:
      - ewm_db_data:/var/lib/postgresql/data

volumes:
  stats_db_data:
  ewm_db_data: