CREATE TABLE IF NOT EXISTS hits (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(512) NOT NULL,
    ip VARCHAR(15) NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_hits_app_uri ON hits (app, uri);
CREATE INDEX IF NOT EXISTS idx_hits_timestamp ON hits (timestamp);
CREATE INDEX IF NOT EXISTS idx_hits_ip ON hits (ip);